apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::822334154166:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::822334154166:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G1YL7EU5U7FC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::822334154166:role/UdacityFlaskDeployCBKubectlRole\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2021-07-12T19:24:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "25834"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 53766a63-8e55-4175-bf44-0ab612fdebd2
